language: csharp
solution: Universe.TinyGZip.sln
mono:
  - latest
install:
  - nuget restore $TRAVIS_SOLUTION
  - sudo apt-get install sysbench -y
  - printenv
script:
  - xbuild $TRAVIS_SOLUTION /t:Rebuild /p:Configuration=Release /verbosity:minimal
  - xbuild $TRAVIS_SOLUTION /t:Rebuild /p:Configuration=Debug   /verbosity:minimal
  - mono --debug --desktop packages/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe --labels=On --workers=1 --work=Universe.TinyGZip.Tests/bin/Debug Universe.TinyGZip.Tests/bin/Debug/Universe.TinyGZip.Tests.dll
  - bash travis-plugins/show-perfomance.sh
  
  